name: Publish playlist

on:
  schedule:
    - cron:  '58 16 * * *'
  watch:
    types: started

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Generate Playlists
      run: |
        
        npm run generate https://raw.githubusercontent.com/wudongdefeng/Apple-IPTV/master/Hongkong.m3u hk.txt
      
        npm run generate https://raw.githubusercontent.com/wing0110210317/MyTV/master/mytv.m3u MyTV.txt
        npm run generate https://raw.githubusercontent.com/expertein/expertein.github.io/master/stream/test.m3u8 test.txt
        npm run generate https://raw.githubusercontent.com/testt2314/test/77f1223ca5834f4695da46f96a908fc19eaf1de0/edited-test.m3u edited-test.txt
    - name: Clean
      run: rm -rf .github && ls -l .

    - name: Git init
      run: |
        git config --global user.name "Actions"
        git config --global user.email "actions@github.com"
 
    - name: Commit
      run: git add --all && git commit -m 'Deploy pages'

    - name: Push to GitHub Pages
      run: git checkout -b gh-pages && git push -f origin gh-pages
